### ISSUE TITLE
Undefined offset: 1 in ...\SWL_CustomTexts.php on line 62

### ISSUE THREAD

**Issue by mwjames** [SemanticMediaWiki/SemanticWatchlist#23] opened 2014-05-27 08:24 UTC
```
46  SWLEmailer::notifyUser( )   ..\GroupNotify.php:133
47  SWLEmailer::getChangeListHTML( )    ..\SWL_Emailer.php:52
48  SWLEmailer::getPropertyHTML( )  ..\SWL_Emailer.php:87
49  SWLCustomTexts->getPropertyCustomText( )    ..\SWL_Emailer.php:112
50  SWLCustomTexts->initCustomTexts( )  ..\SWL_CustomTexts.php:78
```

**Comment by JeroenDeDauw** [comment] 2015-01-30 09:57
@mwjames assuming you have not fixed this.

@nischayn22 can you have a look at this?

**Comment by mwjames** [comment] 2015-01-30 10:00
> assuming you have not fixed this.

No, and given the fact that it has not been converted to a `SWL\` ns.

**Comment by JeroenDeDauw** [comment] 2016-11-26 15:58
Duplicate of https://github.com/SemanticMediaWiki/SemanticWatchlist/issues/59

**Closed by JeroenDeDauw** 2016-11-26 15:58 UTC
Labels: bug
